FORMAT: 1A
HOST: https://api.skladon.cz/v1/

# skladon

Skadon API
Production API url: https://api.skladon.cz/v1/
Test API url: https://test-api.skladon.cz/v1/


## Address Validation Collection [/validation/address-validation]
### List All Address Validation (only for UPS - USA addresses!) [POST]
###### status code 200: valid
###### status code 400: invalid

+ Request (application/json)

        {
            "skladonAuth": {
                "apiKey": "a4de2249-5dal-243v-8r99-623cc54b9616"
            },
            "city": "Cliffside Park", 
            "stateCode":"NJ", 
            "postalCode":"07010"
        }

+ Response 200 (application/json)

        {
            "status": {
                "code": 200,
                "text": "valid"
            }
        }
        
+ Response 200 (application/json)

        {
            "status": {
                "code": 400,
                "text": "invalid"
            }
        }   
        
        
## Create Order Collection [/order/create-order]
### Create Order [POST]
###### status code 200: order successfully created
###### status code 401: order already exists

###### Object properties: 
- orderId: 255 (number, required) - The unique identifier for a order
- message: "Extra stickers ..." (string, required) - Order message for stock-keeper or just left empty string

- shipTo: {} (object, required)
- recipient: {} (object, required)
- recipient: {} (object, required)
- fullName: Miloš Halecký (string, required) - Person name and surname
- attentionName: Miloš Halecký (string, required) - Person Attention name and surname
- address: {} (object, required)
- street: Chemická 955/3 (string, required) - Street
- additionalInformation: second floor (string, reguired) - Additional information or empty string
- city: Prague (string, required) - City name
- countryCode: CZ (string, required) - country code
- provinceCode: CZ (string, required) - province code
- postCode: 14800 (string, required) - postal code 
- email: milos.halecky@gmail.com (string, required) - email address
- companyName: "Company name" (string, required) - company name or empty string
- companyId: "12345678" (string, required) - company id or empty string
- taxId: "12345678" (string, required) - company tax id or empty string
- phone: "00420123123123" (string, required) - phone number in 14 digits format

- invoice: {} (object, optional)
- invoice.invoiceNumber: 40002017 (string, required) - invoice number
- invoice.invoiceDate: 20171231 (string, required) - invoice date format: YYYYMMDD
- invoice.format: pdf (string, required) - invoice format or empty string
- invoice.encoding: base64 (string, required) - invoice data encoding or empty string
- invoice.data: JVBERi0xLjUNJabpz8QgDTkzNCAwIG9iag08PC9... (string, required) - invoice data or empty string

- discount: {} (object, required) - if skladon should provide discount, it has to be discussed otherwise set 0 to value
- discount.type: PER (string, required) - type of discount, PER = percentage
- discount.value: 0 (integer, required) - value of discount

- paid: 1 (integer, required) - 1 = paid, 0 = cash on delivery

- price: {} (object, required)

- price.invoicePrice: {} (object, required)
- price.invoicePrice.value: 50 (integer, required) - ivoice price value
- price.invoicePrice.currency: USD (string, required) - invoice price currency 

- price.shippingPrice: {} (object, required)
- price.shippingPrice.value: 4.00 (number, required) -  shipping price
- price.shippingPrice.currency: USD (string, required) - shipping price currency 

- price.cashOnDelivery: {} (object, optional) - COD Cash On Delivery
- price.cashOnDelivery.value: 4.00 (number, required) -  COD price, Cash On Delivery order price
- price.cashOnDelivery.currency: USD (string, required) - COD price currency 
- price.cashOnDelivery.refNumber: variabilny symbol (string, required) - reference number for bank

- shippingMethod: DEL (string, required) -  shipping method: DEL = Delivery, PER = Personally

- shipper: {} (object, required)
- shipper.name: UPS (string, required) - shipper name according table
- shipper.serviceCode: UPSES (string, required) - shipper service code according table

- products: {} (array, required)
- product.productCode: 1 (string, requried) - The unique identifier, code of product
- product.count: 1 (integer, required) - Count of same products
- product.productPrice: 22 (number, required) - price of one certain product
- product.productCurrency: USD (string, required) - product price currencyta


+ Request (application/json)

        {
            "skladonAuth":{
                "apiKey":"a4de2249-5dal-243v-8r99-623cc54b9616"
        
            },
            "order":{
                "orderId": "255",
                "message": "message text",
                "shipTo":{
                    "recipient": {
                        "fullName": "Miloš Halecký",
                        "attentionName": "Miloš Halecký",
                        "address": {
                            "street": "Chemická 955/3",
                            "additionalInformation": "second floor"
                        },
                        "city": "Prague",
                        "countryCode": "CZ",
                        "provinceCode": "CZ",
                        "postCode": "14800",
                        "email": "milos.halecky@gmail.com",
                        "companyName": "",
                        "companyId": "",
                        "taxId": "",
                        "phone": "00420123123123"
                    },
                    "billing": {
                        "fullName": "Miloš Halecký",
                        "attentionName": "Miloš Halecký",
                        "street": "Chemická 955/3",
                        "city": "Prague",
                        "countryCode": "CZ",
                        "provinceCode": "CZ",
                        "postCode": "14800",
                        "email": "milos.halecky@gmail.com",
                        "companyName": "",
                        "companyId": "",
                        "taxId": "",
                        "phone": "00420735019429"
                    }
                },
                "invoice": {
                    "invoiceNumber":"40002017",
                    "invoiceDate":"20171231",
                    "format":"pdf",
                    "encoding": "base64",
                    "data":"JVBERi0xLjUNJabpz8QgDTkzNCAwIG9iag08PC9MaW5lYXJpemVkIDEvTyA5MzcvSCBbIDgxNSAz"
                },
                "discount":{
                    "type":"PER",
                    "value":"0"
                },
                "paid": 1,
                "price":{
                    "invoicePrice":{
                        "value":"94.00",
                        "currency":"USD"
                    },
                    "shippingPrice":{
                        "value":"4.00",
                        "currency":"USD"
                    },
                    "cashOnDelivery":{
                        "value":"4.00",
                        "currency":"USD",
                        "refNumber":"variabilny symbol"
                    }
                },
                "shippingMethod":"DEL",
                "shipper":{
                    "name":"UPS",
                    "serviceCode": "UPSES"
                        
                },
                "products":[
                    {
                        "productCode":"1",
                        "count":1,
                        "productPrice":"22",
                        "productCurrency":"USD"
                    }

                ]
            }
        } 
        


+ Response 200 (application/json)

        {
            "status": {
                "code": 200,
                "text": "success"
            },
            "response": {
                "message": "order successfully created",
                "invoiceNumber": "40002017"
            }
        }
        
+ Response 200 (application/json)

        {
            "status": {
                "code": 401,
                "text": "error"
            },
            "response":{
                "message": "Order already exists",
                "invoiceNumber": "40002017"
            }
        }

+ Response 200 (application/json)

        {
            "status": {
                "code": 402,
                "text": "error"
            },
            "response": {
                "message": "count of products is less then you need or you don't have any of them stored",
                "products": [1,2]
            }
        }
        
        
## Order State Collection [/order/order-state]
### Order State [POST]
###### status code 300: on the way 
###### status code 301: delivered
###### status code 302: accepted
###### status code 303: in process
###### status code 304: not delivered
###### status code 305: lost
###### status code 306: refunded
###### status code 307: canceled


+ Request (application/json)

        {
            "skladonAuth": {
                "apiKey": "a4de2249-5dal-243v-8r99-623cc54b9616"
            },
            "invoice": {
                    "invoiceNumber":"40002017"
            }
        }

+ Response 200 (application/json)

        {
            "status": {
                "code": 300,
                "text": ""
            },
            "tracking": {
                "number": "tracking_number"
            }
        }
        
+ Response 200 (application/json)

        {
            "status": {
                "code": 301,
                "text": ""
            },
            "tracking": {
                "number": "tracking_number"
            }
        }        
        
+ Response 200 (application/json)

        {
            "status": {
                "code": 302,
                "text": ""
            }
        }
        
+ Response 200 (application/json)

        {
            "status": {
                "code": 303,
                "text": ""
            }
        }
        
## Changes in order state changing Collection [/your-url/{orderID}]
### List All in order state changing [GET]
###### status code 200: OK
###### status code 500: ERROR
###### status code 400: ORDER-NUMBER DOES NOT EXIST

+ Parameters
    + orderID (number) - Order ID
        
+ Response 200 (application/json)

        {
            "status": {
                "code": 200,
                "text": "some-text"
            }
        }
        
+ Response 200 (application/json)

        {
            "status": {
                "code": 500,
                "text": "some-text"
            }
        }
        
+ Response 200 (application/json)

        {
            "status": {
                "code": 400
                "text": "some-text"
            }
        }

## Order Cancellation  [/order/order-cancellation/]
### Order Cancellation [POST]
######  status code 200: order successfully cancelled
######  status code 400: cannot cancel order, reasons: no order found, order was cancelled yet or order is on the way to client

+ Request (application/json)

        {
            "skladonAuth": {
                "apiKey": "a4de2249-5dal-243v-8r99-623cc54b9616"
            },
            "invoice": {
                    "invoiceNumber":"40002017"
            },
        }

+ Response 200 (application/json)

        {
            "status": {
                "code": 200,
                "text": "order successfully cancelled"
            },
            "invoice": {
                    "invoiceNumber":"40002017"
            }
        }
        
+ Response 200 (application/json)

        {
            "status": {
                "code": 400,
                "text": "cannot cancel order, reasons: no order found, order was cancelled yet or order is on the way to client"
            },
            "invoice": {
                    "invoiceNumber":"40002017"
            }
        }        
        
## Product Availability  [/product/products-availability]
### Product Availability [POST]
######  status code 200: product is available, showen count of stored product
######  status code 300: products not founddescripton

+ Request (application/json) 

        {
            "skladonAuth":{
                "apiKey":"a4de2249-5dal-243v-8r99-623cc54b9616"
            },
            "products": [
                {
                "productCode":"1
                }
            ]
        
        }

+ Response 200 (application/json)

        {
            "status": {
                "text": "count of products",
                "code": 200
            },
            "products": [
                {
                    "status": {
                        "text": "available",
                        "statusCode": 1
                    },
                    "productCode": "1",
                    "count": 7
                }
            ]
        }
        
+ Response 200 (application/json)

        {
            "status": {
                "text": "no products found",
                "code": 300
            },
            "products": []
        }