FORMAT: 1A
HOST: https://api.skladon.cz/v1/

# skladon

```
Skadon API
Production API url: https://api.skladon.cz/v1/
Test API url: https://test-api.skladon.cz/v1/
```
```
IMPORTANT: Request - Create Order - with Czech Post carrier can take more than 30 seconds. Please set timeout properly on your http client
```

## Create Order Collection [/order/create-order]
### Create Order [POST]
###### status code 200: order successfully created
###### status code 401: order already exists
###### status code 402: number of products is less then you need or you don't have any of them stored
###### Order is validated. 

###### Object properties: 
- orderId: 255 (number, required) - The unique identifier for the order
- addressId: 175 (number, optional) - address ID of Zasilkovna pickup point
- message: "Extra stickers ..." (string, required) - Order message for stock-keeper or just left empty string
- shipTo: {} (object, required)
    - recipient: {} (object, required)
        - fullName: Miloš Halecký (string, required) - Person name and surname
        - attentionName: Miloš Halecký (string, required) - Person Attention name and surname
        - address: {} (object, required)
            - street: Chemická 955/3 (string, required) - Street
            - additionalInformation: second floor (string, reguired) - Additional information or empty string
        - city: Prague (string, required) - City name
        - countryCode: CZ (string, required) - country code
        - provinceCode: CZ (string, required) - province code
        - postCode: 14800 (string, required) - postal code 
        - email: milos.halecky@gmail.com (string, required) - email address
        - companyName: "Company name" (string, required) - company name or empty string
        - companyId: "12345678" (string, required) - company id or empty string
        - taxId: "12345678" (string, required) - company tax id or empty string
        - phone: "00420123123123" (string, required) - phone number in 14 digits format
    - billing: {} (object, required)
        - fullName: Miloš Halecký (string, required) - Person name and surname
        - attentionName: Miloš Halecký (string, required) - Person Attention name and surname
        - street: Chemická 955/3 (string, required) - Street
        - city: Prague (string, required) - City name
        - countryCode: CZ (string, required) - country code
        - provinceCode: CZ (string, required) - province code
        - postCode: 14800 (string, required) - postal code 
        - email: milos.halecky@gmail.com (string, required) - email address
        - companyName: "Company name" (string, required) - company name or empty string
        - companyId: "12345678" (string, required) - company id or empty string
        - taxId: "12345678" (string, required) - company tax id or empty string
        - phone: "00420123123123" (string, required) - phone number in 14 digits format
- invoice: {} (object, optional)
    - invoiceNumber: 40002017 (string, required) - invoice number
    - invoiceDate: 20171231 (string, required) - invoice date format: YYYYMMDD
    - format: pdf (string, required) - invoice format or empty string
    - encoding: base64 (string, required) - invoice data encoding or empty string
    - data: JVBERi0xLjUNJabpz8QgDTkzNCAwIG9iag08PC9... (string, required) - invoice data or empty string

- discount: {} (object, required) - if skladon should provide discount, it has to be discussed otherwise set 0 to value
    - type: PER (string, required) - type of discount, PER = percentage
    - value: 0 (integer, required) - value of discount

- paid: 1 (integer, required) - 1 = paid, 0 = cash on delivery

- price: {} (object, required)
    - invoicePrice: {} (object, required)
        - value: 1100 (integer, required) - ivoice price value
        - currency: CZK (string, required) - invoice price currency 
    - shippingPrice: {} (object, required)
        - value: 100.00 (number, required) -  shipping price
        - currency: CZK (string, required) - shipping price currency 
    - cashOnDelivery: {} (object, optional) - COD Cash On Delivery
        - value: 1100 (number, required) -  COD price, Cash On Delivery order price
        - currency: CZK (string, required) - COD price currency 
        - refNumber: variabilny symbol (string, required) - reference number for bank

- shippingMethod: DEL (string, required) -  shipping method: DEL = Delivery, PER = Personally. Available = DEL, PER

- shipper: {} (object, required)
    - name: UPS (string, required) - shipper name according table. Available = UPS, CP, GLS, Zasilkovna
    - serviceCode: UPSES (string, required) - shipper service code according table. Available = UPSES, CPDR, CPDRCOD, CPNP, CPNPCOD, RRCZ, RRCZCOD, RREU, RRWR, GLSCZ, GLSCZCOD, GLSEU, GLSEUCOD, TGCZ, TGCZCOD, TGEU, TGEUCOD, PCKT

- products: [] (array, required)
    - productCode: 1 (string, requried) - The unique identifier, code of product
    - count: 1 (integer, required) - Count of same products
    - productPrice: 22 (number, required) - price of one certain product
    - productCurrency: USD (string, required) - product price currencyta


+ Request (application/json)

        {
            "skladonAuth":{
                "apiKey":"a4de2249-5dal-243v-8r99-623cc54b9616"
        
            },
            "order":{
                "orderId": "255",
                "addressId": 175,
                "message": "message text",
                "shipTo":{
                    "recipient": {
                        "fullName": "Miloš Halecký",
                        "attentionName": "Miloš Halecký",
                        "address": {
                            "street": "Chemická 955/3",
                            "additionalInformation": "second floor"
                        },
                        "city": "Prague",
                        "countryCode": "CZ",
                        "provinceCode": "CZ",
                        "postCode": "14800",
                        "email": "milos.halecky@gmail.com",
                        "companyName": "",
                        "companyId": "",
                        "taxId": "",
                        "phone": "00420123123123"
                    },
                    "billing": {
                        "fullName": "Miloš Halecký",
                        "attentionName": "Miloš Halecký",
                        "street": "Chemická 955/3",
                        "city": "Prague",
                        "countryCode": "CZ",
                        "provinceCode": "CZ",
                        "postCode": "14800",
                        "email": "milos.halecky@gmail.com",
                        "companyName": "",
                        "companyId": "",
                        "taxId": "",
                        "phone": "00420735019429"
                    }
                },
                "invoice": {
                    "invoiceNumber":"40002017",
                    "invoiceDate":"20171231",
                    "format":"pdf",
                    "encoding": "base64",
                    "data":"JVBERi0xLjUNJabpz8QgDTkzNCAwIG9iag08PC9MaW5lYXJpemVkIDEvTyA5MzcvSCBbIDgxNSAz"
                },
                "discount":{
                    "type":"PER",
                    "value":"0"
                },
                "paid": 0,
                "price":{
                    "invoicePrice":{
                        "value":"1100.00",
                        "currency":"CZK"
                    },
                    "shippingPrice":{
                        "value":"100.00",
                        "currency":"CZK"
                    },
                    "cashOnDelivery":{
                        "value":"1100.00",
                        "currency":"CZK",
                        "refNumber":"variabilny symbol"
                    }
                },
                "shippingMethod":"DEL",
                "shipper":{
                    "name":"UPS",
                    "serviceCode": "UPSES"
                        
                },
                "products":[
                    {
                        "productCode":"1",
                        "count":1,
                        "productPrice":"22",
                        "productCurrency":"USD"
                    }

                ]
            }
        } 
        


+ Response 200 (application/json)

        {
            "status": {
                "code": 200,
                "text": "success"
            },
            "response": {
                "message": "order successfully created",
                "orderId": "123"
            }
        }
        
+ Response 200 (application/json)

        {
            "status": {
                "code": 401,
                "text": "error"
            },
            "response":{
                "message": "Order already exists",
                "orderId": "123"
            }
        }

+ Response 200 (application/json)

        {
            "status": {
                "code": 402,
                "text": "error"
            },
            "response": {
                "message": "number of products is less then you need or you don't have any of them stored",
                "products": [1,2]
            }
        }
        
+ Response 400 (application/json)

        {
            "name": {
                "code": 403,
                "text": "ValidationError"
            },
            "response": {
                "details": [
                    {
                        "message": "\"fullName\" is required",
                        "path": "order.shipTo.recipient.fullName",
                        "type": "any.required",
                        "context": {
                            "key": "fullName"
                        }
                    }
                ],
                "body": {
                    "skladonAuth": "automatically hidden",
                    "order": {
                        "orderId": "255",
                        "message": "message text",
                        "shipTo": {
                            "recipient": {
                                "attentionName": "Miloš Halecký",
                                "address": {
                                    "street": "Chemická 955/3",
                                    "additionalInformation": "second floor"
                                },
                                "city": "Prague",
                                "countryCode": "CZ",
                                "provinceCode": "",
                                "postCode": "14800",
                                "email": "milos.halecky@gmail.com",
                                "companyName": "",
                                "companyId": "",
                                "taxId": "",
                                "phone": "00420123123123"
                            },
                            "billing": {
                                "fullName": "Miloš Halecký",
                                "attentionName": "Miloš Halecký",
                                "street": "Chemická 955/3",
                                "city": "Prague",
                                "countryCode": "CZ",
                                "provinceCode": "",
                                "postCode": "14800",
                                "email": "milos.halecky@gmail.com",
                                "companyName": "",
                                "companyId": "",
                                "taxId": "",
                                "phone": "00420123123123"
                            }
                        },
                        "invoice": {
                            "invoiceNumber":"40002017",
                            "invoiceDate":"20171231",
                            "format":"pdf",
                            "encoding": "base64",
                            "data":"JVBERi0xLjUNJabpz8QgDTkzNCAwIG9iag08PC9MaW5lYXJpemVkIDEvTyA5MzcvSCBbIDgxNSAz"
                        },
                        "discount": {
                            "type": "PER",
                            "value": 0
                        },
                        "paid": 0,
                        "price":{
                            "invoicePrice":{
                                "value":"840.00",
                                "currency":"CZK"
                            },
                            "shippingPrice":{
                                "value":"40.00",
                                "currency":"CZK"
                            },
                            "cashOnDelivery":{
                                "value":"840.00",
                                "currency":"USD",
                                "refNumber":"variabilny symbol"
                            }
                        },
                        "shippingMethod": "DEL",
                        "shipper": {
                            "name": "UPS",
                            "serviceCode": "UPSES"
                        },
                        "products": [
                            {
                                "productCode":"1",
                                "count":1,
                                "productPrice":"22",
                                "productCurrency":"USD"
                            }
                        ]
                    }
                }
            }
        }
        
        
## Order State Collection [/order/order-state]
### Order State [POST]
###### status code 300: on the way 
###### status code 301: delivered
###### status code 302: accepted
###### status code 303: in process
###### status code 304: not delivered
###### status code 305: lost
###### status code 306: refunded
###### status code 307: canceled


+ Request (application/json)

        {
            "skladonAuth": {
                "apiKey": "a4de2249-5dal-243v-8r99-623cc54b9616"
            },
            "invoice": {
                    "invoiceNumber":"40002017"
            }
        }

+ Response 200 (application/json)

        {
            "status": {
                "code": 300,
                "text": ""
            },
            "tracking": {
                "number": "tracking_number"
            }
        }
        
+ Response 200 (application/json)

        {
            "status": {
                "code": 301,
                "text": ""
            },
            "tracking": {
                "number": "tracking_number"
            }
        }        
        
+ Response 200 (application/json)

        {
            "status": {
                "code": 302,
                "text": ""
            }
        }
        
+ Response 200 (application/json)

        {
            "status": {
                "code": 303,
                "text": ""
            }
        }
        
## Product Availability  [/product/products-availability]
### Product Availability [POST]
######  status code 200: product is available, showen count of stored product
######  status code 404: product not found

+ Request (application/json) 

        {
            "skladonAuth":{
                "apiKey":"a4de2249-5dal-243v-8r99-623cc54b9616"
            },
            "products": [
                {
                    "productCode":"1"
                },
                {
                    "productCode":"10000001"
                }
            ]
        
        }

+ Response 200 (application/json)

        {
            "status": {
                "text": "count of products",
                "code": 200
            },
            "products": [
                {
                    "status": "OK",
                    "code": 200,
                    "productCode": "1",
                    "count": 0
                },
                {
                    "status": "Not found",
                    "code": 404,
                    "productCode": "10000001",
                    "count": null
                },
            ]
        }
        
+ Response 500 (application/json)

        {
            "statusCode":500,
            "error":"Internal Server Error",
            "message":"An internal server error occurred"
        }
        

## Order update [/order/update]
### Order update [PUT]
```
For update order just set attribute what do you want to edit.
For example if I want set different shipper see request.
```
+ Request (application/json) 

        {
            "skladonAuth":{
                "apiKey":"a4de2249-5dal-243v-8r99-623cc54b9616"
            },
            "object": {
                {
                    "order":{
                        "SHIPPER": "CP",
                        "ID":35479
                    }
                }
            }
        
        }

+ Response 200 (application/json)

        {
           "ID":35479,
           "ESHOP_ORDER_ID":"255",
           "ESHOP_KEY":"a4de2249-5dal-243v-8r99-623cc54b9616",
           "ORDER_DATE":"20190411",
           "TRACKING_NUMBER":"DR7042421396L",
           "TIMESTAMP":"2019-04-11T12:50:36.000Z",
           "STATUS":"inProcess",
           "SUB_STATUS":null,
           "RECIPIENT_NAME":"Miloš Halecký",
           "RECIPIENT_ATTENTION_NAME":"Miloš Halecký",
           "RECIPIENT_EMAIL":"milos@milos.cz",
           "RECIPIENT_PHONE":"735999999",
           "RECIPIENT_COMPANY_NAME":"",
           "RECIPIENT_COMPANY_ID":"0",
           "RECIPIENT_TAX_ID":"",
           "RECIPIENT_STREET":"Chemická 955/3",
           "RECIPIENT_ADDRESS_ADDITIONAL_INFO":null,
           "RECIPIENT_CITY":"Praha",
           "RECIPIENT_STATE":"CZ",
           "RECIPIENT_PROVINCE_CODE":"",
           "RECIPIENT_POST_CODE":"14800",
           "BILLING_NAME":"Miloš Halecký",
           "BILLING_ATTENTION_NAME":"Miloš Halecký",
           "BILLING_EMAIL":"milos@milos.cz",
           "BILLING_PHONE":"735999999",
           "BILLING_COMPANY_NAME":"",
           "BILLING_COMPANY_ID":"0",
           "BILLING_TAX_ID":"",
           "BILLING_STREET":"Chemická 955/3",
           "BILLING_ADDRESS_ADDITIONAL_INFO":null,
           "BILLING_CITY":"Praha",
           "BILLING_STATE":"CZ",
           "BILLING_PROVINCE_CODE":"",
           "BILLING_POST_CODE":"14800",
           "SHIPPER":"CP",
           "WEIGHT":null,
           "UNIT":null,
           "PRICE":"500.00",
           "SHIPPING_PRICE":"78.26",
           "CURRENCY":"CZK",
           "SHIPPING_CURRENCY":"CZK",
           "PAID":1,
           "METHOD":"DEL",
           "SHIPPER_SERVICE_CODE":"CPDR",
           "BOX_ID":null,
           "COD_PRICE":"0.00",
           "COD_CURRENCY":"",
           "COD_REF_NUMBER":"",
           "MESSAGE":"",
           "SHIPPER_ZONE":-1,
           "SHIPPED_AT":null,
           "IN_PROCESS_AT":null,
           "DELIVERED_AT":null,
           "INVOICE_NUMBER":null,
           "ADDRESS_ID":null,
           "SHIPPER_LABEL_PRINTED":0,
           "ORDER_TYPE":"b2c",
           "DELIVERED_HOOK":null,
           "INCORRECT_ORDER_MESSAGE":null,
           "DCIX_EXPORT":"2019-04-11T13:42:39.000Z",
           "DCIX_IMPORT":null,
           "PERSONAL_INFORMATION_ENCODE":null,
           "PERSONAL_INFORMATION_DECODE":null,
           "PROVIDER":{
              "ID":2,
              "ESHOP_KEY":"a4de2249-5dal-243v-8r99-623cc54b9616",
              "VIRTUAL_ESHOP_PARENT":null,
              "COMPANY_NAME":"Eshop",
              "WEBSITE":"eshop.com",
              "PROVIDER_STREET":"unknown",
              "PROVIDER_CITY":"unknown",
              "PROVIDER_STATE":"unknown",
              "PROVIDER_POST_CODE":"12312",
              "PROVIDER_COMPANY_ID":12345698,
              "PROVIDER_TAX_ID":"CZ12345698",
              "PROVIDER_BILLING_STREET":"unknown",
              "PROVIDER_BILLING_CITY":"unknown",
              "PROVIDER_BILLING_STATE":"unknown",
              "PROVIDER_BILLING_POST_CODE":"12312",
              "PROVIDER_COMPANY_PHONE":"unknown",
              "BANK_ACCOUNT_NO":"unknown",
              "LOGO":null,
              "ACTIVE":1,
              "PROVIDER_EMAIL":"info@eshop.com",
              "SHOPTET":0,
              "INITIAL_SHOPTET_IMPORT_PRODUCT":null,
              "SHOPTET_STOCK_ID":null,
              "DCIX_PROVIDER_ID":3
           },
           "ORDER_PRODUCTS":[
              {
                 "ORDERS_PRODUCTS_ID":44267,
                 "PRODUCT_ID":69,
                 "ORDER_ID":35479,
                 "COUNT":"1",
                 "PRODUCT_PRICE":"410.00",
                 "PRODUCT_CURRENCY":"CZK",
                 "ITEMS":[
                    {
                       "ID":1,
                       "PRODUCT_ID":1,
                       "STOCK_POSITION":null,
                       "STOCK_ID":3,
                       "UNIT":"ks",
                       "ALL":"80.000000",
                       "ALLOCATED":"51.000000",
                       "AWAITING":"6.000000",
                       "RECEIVED":"0.000000",
                       "AVAILABLE":"14.000000",
                       "LOT":"",
                       "EXPIRATION_DATE":null,
                       "DCIX_EXPORT":"2019-04-17T21:06:38.000Z"
                    }
                 ],
                 "PRODUCT":{
                    "ID":1,
                    "SKU":"1",
                    "OWNER_ESHOP_KEY":"a4de2249-5dal-243v-8r99-623cc54b9616",
                    "ALIAS":null,
                    "NAME":"Product 1",
                    "DESCRIPTION":"Product",
                    "PRICE":null,
                    "UNIT_PRICE":"",
                    "UNIT_WEIGHT":"kg",
                    "WIDTH":null,
                    "HEIGHT":null,
                    "LENGTH":null,
                    "WEIGHT":"0.097000",
                    "HS_CODE":"21069098",
                    "UPC":null,
                    "EAN":null,
                    "ROP":0,
                    "STOCK_MU_CODE":"pcs",
                    "EXP_METHOD":"FIFO",
                    "DCIX_IMPORT":null,
                    "MPN":null,
                    "ISBN":null,
                    "NOTE":null,
                    "ACTIVE":1,
                    "PACKING_TYPE":"pickandpack",
                    "INSERT_TO_PRODUCT_ID":null,
                    "PACKAGING_MATERIAL_SLOTS":null,
                    "PRODUCT_TYPE":"item",
                    "INSERT_TYPE":null,
                    "CREATED_AT":"2019-02-15T00:15:27.000Z",
                    "UPDATED_AT":"2019-04-13T14:30:07.000Z"
                 }
              }
           ],
              "shipper":"CP",
              "trackingNumber":"DR7042421396L",
              "success":true
           }
        }

## Create product [/product/create]
### Create product [PUT]

+ Request (application/json)

        {
            "skladonAuth":{
                "apiKey":"a4de2249-5dal-243v-8r99-623cc54b9616"
            },
            "object": {
                "product":{
                      "SKU":"SKU1",
                      "NAME":"Product name 1",
                      "DESCRIPTION":"Description 1",
                      "PRICE":null,
                      "WIDTH":null,
                      "HEIGHT":null,
                      "LENGTH":null,
                      "WEIGHT":null,
                      "HS_CODE":null,
                      "UNIT_PRICE":null,
                      "UNIT_WEIGHT":null,
                      "UPC":null,
                      "EAN":null,
                      "ROP":null,
                      "MPN":null,
                      "ISBN":null,
                      "NOTE":null,
                      "ACTIVE":1,
                      "ITEMS":[],
                      "PACKING_TYPE":"slapalabel",
                      "INSERT_TO_PRODUCT_ID":null,
                      "PRODUCT_TYPE":"item",
                      "INSERT_TYPE":null,
                      "PHOTO_HASH":null,
                      "ROP ":"100"
                }
            }
        
        }
        
+ Response 200 (application/json)

        {
           "SKU":"SKU1",
           "OWNER_ESHOP_KEY":"a4de2249-5dal-243v-8r99-623cc54b9616"
           "NAME":"Product name 1",
           "DESCRIPTION":"Description 1",
           "PRICE":null,
           "UNIT_PRICE":null,
           "UNIT_WEIGHT":null,
           "WIDTH":null,
           "HEIGHT":null,
           "LENGTH":null,
           "WEIGHT":null,
           "HS_CODE":null,
           "UPC":null,
           "EAN":null,
           "ROP":0,
           "MPN":null,
           "ISBN":null,
           "NOTE":null,
           "ACTIVE":1,
           "PACKING_TYPE":"slapalabel",
           "INSERT_TO_PRODUCT_ID":null,
           "PRODUCT_TYPE":"item",
           "INSERT_TYPE":null,
           "UPDATED_AT":"2019-05-06T14:00:08.000Z",
           "CREATED_AT":"2019-05-06T14:00:08.000Z",
           "ITEMS":[],
           "ID":516,
           "STOCK_MU_CODE":"pcs",
           "PHOTO_HASH":null
        }